package main;

public enum Direction {
	MOVE, JUMP, // FUCK IT
	BLOCK, // BLOCK, GAIN A BIT HEALTH
	ATTACK, // NORMAL ATTACK
	CLOSERANGE, // CLOSE RANGE ATTACK
	POWER, // STRONG ATTACK, MOST LIKELY NOT TO SUCSEED
	SLEEP, // WAIT A TURN AND RETURN HEALTH AND STAMINA
	CHARGE, // THIS IS SPARTAAA - GO FORWARD AND ATTACK
	ARROW, SWITCH, PUSH,

	RIGHT, LEFT

}
